### ISSUE TITLE
Use TLS/SSL for node state query

### ISSUE THREAD

**Issue by VortexUK** [paychex/prometheus-emcecs-exporter#4]
(Requested from other issue)

Currently the code is using the non-encrypted port (9020) to do the node look up - if it is possible look in to ways of getting the node ips using the MGT api instead. If it is necessary do hit the 'data' api, use the SSL (9021) by default, or have a flag to turn it on

Thanks!

**Comment by xphyr** [comment]
The 1.2 release has a fix for this and uses SSL by default.  Closing out this issue.
