### ISSUE TITLE
launching exporter?

### ISSUE THREAD

**Issue by jackdawheart** [paychex/prometheus-emcecs-exporter#5]
I'm not really familiar with golang, so this is a pretty basic question. Once I run the  go get -u github.com/paychex/prometheus-emcecs-exporter/... command, how do I actually launch the exporter? I tried to use go run, but I get the error:
package prometheus-emcecs-exporter: no Go files in /home/<username>/go/src/prometheus-emcecs-exporter.

thanks!

**Comment by jackdawheart** [comment]
Alright, I found the solution to this too. My mistake here was to try to pass the vars as arguments to the command. What you actually have to do is to go to /home/username/go/src/prometheus-emcecs-exporter/pkg/config and edit the config.go file to insert the parameters there.

One other issue I ran in to was that on starting the exported I kept getting a context dealine exceeded error - I fixed that by adding - scrape_timeout: 10s to the prometheus config file settings for the emcecs job.

**Comment by xphyr** [comment]
@jackdawheart So there is a better way to run the exporter, that does not require changing the source.  I think I need to do a little work on updating the README.md file to make this more clear.  I may also be able to set up a binary distribution like I did for the Isilon exporter.  Give me a few days and I will update the readme to make it a little more clear and I will ping you again to see if the updates help.

**Comment by jackdawheart** [comment]
@xphyr thanks for taking a look!

**Comment by xphyr** [comment]
@jackdawheart sorry it took me a bit longer than I wanted to get back to this.  I have added this section: https://github.com/paychex/prometheus-emcecs-exporter#running-the-exporter to the docs. Can you review this and let me know if it answers your questions and hopefully makes it easier for you to consume the exporter.

**Comment by jackdawheart** [comment]
Thanks for this - I'm going to test out the standalone setup and get back to you with the results

**Comment by xphyr** [comment]
@jackdawheart I have not heard back on this, so I am planning to close out the issue.  Please let me know if you need me to re-open it.
